import {mkdtempSync, mkdirSync} from 'node:fs';
import {join} from 'node:path';
import {spawn} from 'node:child_process';
import {desktopRequire} from '../src/desktop-adapter/stable/modules.mjs';
import {repository} from '../src/desktop-adapter/paths.mjs';
import {smokeEnvironment} from './smoke-environment.mjs';
mkdirSync(join(repository, '.runtime'), {recursive: true});
const root = mkdtempSync(join(repository, '.runtime/updates-'));
const env = smokeEnvironment({DSH_PROJECT_DESKTOP_SMOKE_DATA: root});
console.log('Update UI evidence:', root);
const child = spawn(desktopRequire('electron'), [repository, '--update-test'], {env, stdio: 'inherit'});
child.on('error', error => {console.error(error); process.exitCode = 1});
child.on('exit', code => {process.exitCode = code ?? 1});
